#!/bin/sh

GUNICORN=/usr/local/bin/gunicorn
# 项目目录
ROOT=/home/group/gotit_new
# 进程PID
PID=/var/run/gunicorn_new_gotit.pid

APP=code:application

# 监听的IP及端口
IP=127.0.0.1:6666

if [ -f $PID ]; then
    rm $PID
fi

cd $ROOT
#exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID $APP -D -b $IP
exec $GUNICORN --pid=$PID $APP -D -b $IP
